image: docker:stable

stages:
  - build
  - test

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build
  services:
    - docker:dind
  variables:
    CI_DEBUG_TRACE: "true"
    DOCKER_DRIVER: overlay2
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $IMAGE:latest || true
    - docker build
        --cache-from $IMAGE:latest
        --tag $IMAGE:latest
        --file ./Dockerfile.prod
        "."
    - docker push $IMAGE:latest


test:
  stage: test
  image: $IMAGE:latest
  services:
    - postgres:latest
  variables:
    CI_DEBUG_TRACE: "true"
    POSTGRES_DB: users
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: runner
    DATABASE_TEST_URL: postgresql://runner?runner@postgres:5432/users
  script:
    - pytest "src/tests" - no:warnings
    - flake8 src
    - black src --check
    - isort src --check-only

